basePath: /api/v1
definitions:
  models.Album:
    properties:
      artist:
        type: string
      id:
        type: string
      price:
        type: number
      title:
        type: string
    type: object
  models.AlbumList:
    properties:
      albums:
        items:
          $ref: '#/definitions/models.Album'
        type: array
    type: object
info:
  contact: {}
  description: Test Album API.
  title: Album API
paths:
  /albums:
    get:
      consumes:
      - application/json
      description: get all albums
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AlbumList'
      summary: List albums
      tags:
      - albums
    post:
      consumes:
      - application/json
      description: post albums
      parameters:
      - description: post albums
        in: body
        name: album
        required: true
        schema:
          $ref: '#/definitions/models.Album'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Album'
      summary: create album
      tags:
      - albums
  /albums/{id}:
    get:
      consumes:
      - application/json
      description: Get albums by Id
      parameters:
      - description: album ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Album'
      summary: get albums by id
      tags:
      - albums
schemes:
- http
- https
swagger: "2.0"
